### Importing required libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.ensemble import RandomForestClassifier   
from xgboost import XGBClassifier

#### About the dataset

1. age

2. sex

3. chest pain type (4 values)

4. resting blood pressure

5. serum cholestoral in mg/dl

6. fasting blood sugar > 120 mg/dl

7. resting electrocardiographic results (values 0,1,2)

8. maximum heart rate achieved

9. exercise induced angina

10. oldpeak = ST depression induced by exercise relative to rest

11. the slope of the peak exercise ST segment

12. number of major vessels (0-3) colored by flourosopy

13. thal: 0 = normal; 1 = fixed defect; 2 = reversable defect The names and social security numbers of the patients were recently removed from the database, replaced with dummy values.

### Data Collection & Preprocessing

In [3]:
df = pd.read_csv("heart_disease_data.csv",encoding_errors='ignore')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

#### No. of Rows and Columns

In [4]:
df.shape

(303, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

#### Checking for null values

In [6]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

#### Analysis of all numerical columns

In [7]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [8]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

##### Spliting the data into Features and Target columns

In [9]:
X = df.drop('target',axis=1)
y = df['target']

#### Spliting the data into Train data and Test data

In [10]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=3)

#### Scaling the Data

In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)  
X_test = scaler.transform(X_test)

### Model = Logistic Regression

In [12]:
model_lr = LogisticRegression()
model_lr.fit(X_train,y_train)
y_pred = model_lr.predict(X_test)
score = accuracy_score(y_pred,y_test)
print(f"Accuracy score of Logistic Regression model is:{score}")

Accuracy score of Logistic Regression model is:0.8791208791208791

### Model = Support Vector Machine

In [13]:
model_svm = SVC()
model_svm.fit(X_train,y_train)
y_pred = model_svm.predict(X_test)
score = accuracy_score(y_pred,y_test)
print(f"Accuracy score of Support Vector Machine model is:{score}")

Accuracy score of Support Vector Machine model is:0.8461538461538461

### Model = Random Forest

In [14]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)
y_pred = model_rf.predict(X_test)
score = accuracy_score(y_pred,y_test)
print(f"Accuracy score of Random Forest model is:{score}")

Accuracy score of Random Forest model is:0.8131868131868132

### Model = XGBoost

In [15]:
model_xgb = XGBClassifier()
model_xgb.fit(X_train,y_train)
y_pred = model_xgb.predict(X_test)
score = accuracy_score(y_pred,y_test)
print(f"Accuracy score of XGBoost model is:{score}")

Accuracy score of XGBoost model is:0.8351648351648352

### Building a Predictive System

In [16]:
input_data = (62,0,0,140,268,0,0,160,0,3.6,0,2,2)

input_data_as_numpy_array= np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model_lr.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[0]
The Person does not have a Heart Disease

### Saving the Model

In [17]:
import pickle

filename = "trained_model.sav"

with open(filename, "wb") as f:
    pickle.dump(model_lr, f)

In [18]:
loaded_model = pickle.load(open("trained_model.sav",'rb'))